#!/usr/bin/python3

import sys
import time
import threading


def factorize(number):
    factors = []
    for i in range(2, number // 2 + 1):
        if number % i == 0:
            factors.append((i, number // i))
            return factors


def main(filename):
    try:
        processed_numbers = set()
        with open(filename, 'r') as file:
            for line in file:
                number = int(line.strip())
                if number not in processed_numbers:
                    factorizations = factorize(number)
                    if factorizations:
                        for factors in factorizations:
                            p, q = factors
                            print(f"{number}={p}*{q}")
                    else:
                        print(f"{number} is prime.")
                    processed_numbers.add(number)
    except FileNotFoundError:
        print(f"File '{filename}' not found.")
    except ValueError:
        print("Invalid input. Please use num>1.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        filename = sys.argv[1]

        timer_thread = threading.Timer(5, lambda: sys.exit(0))
        timer_thread.start()

        start_time = time.time()
        main(filename)
        end_time = time.time()
        elapsed_time = end_time - start_time
